"""Emit the complete bounded dependency graphs for rigid gameplay equipment."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
ORDER=('divine_shield','sheikah_shield','shield_of_ikana','cane_of_byrna','trident',
       'four_sword_blade','four_sword_hilt','iron_knuckle_axe')

def generate():
    base=ROOT/'soh/assets/custom'
    groups=[]
    for slug in ORDER:
        folder=base/'objects/nei_held_redesign'/slug
        files=sorted(p.relative_to(base).as_posix() for p in folder.iterdir() if p.is_file())
        assert files and all('/' in f for f in files),slug
        groups.append(files)
    width=max(map(len,groups))+1
    lines=['#ifndef NEI_EQUIPMENT_DEPENDENCIES', '#define NEI_EQUIPMENT_DEPENDENCIES', '// Generated by tools/nei_held/generate_equipment_manifest.py; do not edit.',
           'static const char* const sNeiEquipmentResources[NEI_EQUIPMENT_COUNT]['+str(width)+'] = {']
    for slug,files in zip(ORDER,groups):
        lines.append('    { // '+slug)
        lines.extend('        "__OTR__'+f+'",' for f in files)
        lines.append('        NULL\n    },')
    lines.append('};\n#endif\n')
    text='\n'.join(lines)
    for host in ['soh','mm']:
        (ROOT/host/'mods/equipment/nei_equipment_resources.inc').write_text(text)

if __name__=='__main__':generate()
