#!/usr/bin/env python3
"""Record native horse display-list contracts, without copying any asset payload into the source tree."""

import argparse
from pathlib import Path

from run_epona_cosmetics_tests import native_lists

ROOT = Path(__file__).resolve().parents[2]


def fingerprint(commands):
    value = 14695981039346656037
    for command in commands:
        for word in command:
            for byte in word.to_bytes(4, "little"):
                value = ((value ^ byte) * 1099511628211) & 0xFFFFFFFFFFFFFFFF
    return value


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--oot", required=True, type=Path)
    parser.add_argument("--mm", required=True, type=Path)
    parser.add_argument("--output", type=Path, default=ROOT / "combo/EponaCosmeticsNativeTemplates.h")
    args = parser.parse_args()
    templates = []
    operands = []
    for game, archive in (("oot", args.oot), ("mm", args.mm)):
        _, lists, _ = native_lists(archive, game)
        for name, young, commands in lists:
            start = len(operands)
            i = 0
            while i < len(commands):
                opcode = commands[i][0] >> 24
                if opcode in (0x20, 0x32):
                    operands.append((i, commands[i][1]))
                i += 2 if opcode in (0x20, 0x31, 0x32, 0x33) else 1
            templates.append((name, commands, game == "mm", start, len(operands) - start))
    text = '''// Generated by build_epona_native_templates.py from the native OoT/MM display lists.
// A custom binary list may leave IsCustom=false. Verify its whole command layout
// before using fixed UV masks, especially texture-load sizes that the renderer trusts.
#pragma once

#include <libultraship/libultra/gbi.h>
#include <cstdint>
#include <string_view>
#include <vector>

namespace EponaCosmetics {
struct NativeCacheOperand {
    uint16_t index;
    uint32_t original;
};
inline constexpr NativeCacheOperand kNativeCacheOperands[] = {
'''
    for index, original in operands:
        text += f'    {{ {index}, 0x{original:08X} }},\n'
    text += '''};
struct NativeTemplate {
    std::string_view path;
    uint64_t fingerprint;
    size_t commands;
    bool mm;
    size_t cacheFirst;
    size_t cacheCount;
};
inline constexpr NativeTemplate kNativeTemplates[] = {
'''
    for name, commands, mm, first, count in templates:
        text += f'    {{ "{name}", 0x{fingerprint(commands):016X}ULL, {len(commands)}, {str(mm).lower()}, {first}, {count} }},\n'
    text += '''};

inline bool NativeTemplateMatches(std::string_view path, const std::vector<Gfx>& commands, bool mm) {
    if (path.starts_with("__OTR__")) {
        path.remove_prefix(7);
    }
    for (const auto& expected : kNativeTemplates) {
        if (expected.path != path || expected.mm != mm || expected.commands != commands.size()) {
            continue;
        }
        uint64_t fingerprint = 14695981039346656037ULL;
        size_t cacheIndex = expected.cacheFirst;
        for (size_t index = 0; index < commands.size(); ++index) {
            const auto& command = commands[index];
            uintptr_t operand = command.words.w1;
            if (cacheIndex < expected.cacheFirst + expected.cacheCount &&
                kNativeCacheOperands[cacheIndex].index == index) {
                // Fast3D replaces these exact SETTIMG_HASH/VTX_HASH operands with host pointers.
                // Normalize only a cached pointer; a changed native offset must still be rejected.
                if (operand > 0xFFFFF) {
                    operand = kNativeCacheOperands[cacheIndex].original;
                }
                ++cacheIndex;
            }
            for (const auto word : { command.words.w0, operand }) {
                if (static_cast<uint64_t>(word) > UINT32_MAX) {
                    return false;
                }
                for (unsigned shift = 0; shift < 32; shift += 8) {
                    fingerprint = (fingerprint ^ ((word >> shift) & 0xFF)) * 1099511628211ULL;
                }
            }
        }
        return fingerprint == expected.fingerprint;
    }
    return false;
}
} // namespace EponaCosmetics
'''
    args.output.write_text(text)
    print(f"Wrote native command-layout contracts: {args.output}")


if __name__ == "__main__":
    main()
