"""Generate immutable Epona semantic masks from the native OoT/MM texture resources.

Only one bit per native texel is retained; original artwork is not embedded. Runtime
blended-texture masks select the same UV regions on native and replacement textures.
"""
import argparse
from pathlib import Path
import struct
import zipfile


def decode(archive, path, palette=None):
    data = archive.read(path)
    fmt, width, height, size = struct.unpack_from("<4I", data, 64)
    pixels = data[80:80 + size]
    if fmt == 2:
        colors = [((v >> 11) * 255 // 31, ((v >> 6) & 31) * 255 // 31, ((v >> 1) & 31) * 255 // 31)
                  for (v,) in struct.iter_unpack(">H", pixels)]
    elif fmt == 4:
        colors = [palette[v] for v in pixels]
    elif fmt == 6:
        colors = [(v, v, v) for v in pixels]
    else:
        raise ValueError(f"Unsupported native texture format {fmt}: {path}")
    assert len(colors) == width * height
    return width, height, colors


def is_coat(rgb):
    r, g, b = rgb
    return r > g + 20 and r > b + 20


def is_hair(rgb):
    r, g, b = rgb
    return g * 5 >= r * 4 and b * 20 >= r * 13 and max(rgb) > 28


def is_iris(rgb):
    # The native iris is a dark neutral ring. Pure-black pupil/lashes and bright
    # reflection pixels stay untouched; orange eyelids belong to Coat.
    return max(rgb) - min(rgb) <= 12 and 15 < max(rgb) < 160


def build(oot_path, mm_path):
    masks, entries = [], []

    def add(archive, path, role, palette=None):
        width, height, pixels = decode(archive, path, palette)
        parts = []
        for part in range(3):
            selected = []
            for i, rgb in enumerate(pixels):
                keep = False
                if part == 0:
                    keep = role == "coat" or (role in ("mixed", "hair", "eye", "closed") and is_coat(rgb))
                    if role == "girth":
                        keep = i % width >= 18 and is_coat(rgb)
                elif part == 1:
                    keep = role == "hair" and is_hair(rgb)
                elif part == 2:
                    keep = role == "eye" and is_iris(rgb)
                selected.append(keep)
            if not any(selected):
                parts.append("nullptr")
                continue
            rows = tuple(sum(1 << x for x in range(width) if selected[y * width + x]) for y in range(height))
            mask = (width, height, rows)
            if mask not in masks:
                masks.append(mask)
            parts.append(f"&kMasks[{masks.index(mask)}]")
        entries.append((path.rsplit("/", 1)[-1], parts))

    with zipfile.ZipFile(oot_path) as oot, zipfile.ZipFile(mm_path) as mm:
        adult = "objects/object_horse/"
        adult_palette = decode(oot, adult + "gEponaEyeTLUT")[2]
        for name in ("Chest", "Neck", "Shoulder", "Thigh", "Hair"):
            add(oot, adult + "gEpona" + name + "Tex", "coat")
        for name in ("Crest", "Mane", "Feathering"):
            add(oot, adult + "gEpona" + name + "Tex", "hair")
        for name in ("Forehead", "Nostrils"):
            add(oot, adult + "gEpona" + name + "Tex", "mixed")
        add(oot, adult + "gEponaSaddleGirthTex", "girth")
        for state in ("Open", "Half", "Closed"):
            add(oot, adult + "gEponaEye" + state + "Tex", "closed" if state == "Closed" else "eye", adult_palette)

        young = "objects/object_horse_link_child/"
        roles = {"001F68": "hair", "002168": "hair", "002368": "hair", "002568": "coat",
                 "002588": "mixed", "002788": "mixed", "008120": "coat", "008320": "coat"}
        for suffix, role in roles.items():
            add(oot, young + "object_horse_link_childTex_" + suffix, role)
            mm_suffix = {"008120": "00DAF0", "008320": "00DCF0"}.get(suffix, suffix)
            add(mm, young + "object_horse_link_child_Tex_" + mm_suffix, role)
        child_palette = decode(oot, young + "gChildEponaEyeTLUT")[2]
        for state in ("Open", "Half", "Close"):
            add(oot, young + "gChildEponaEye" + state + "Tex", "closed" if state == "Close" else "eye", child_palette)
        # MM uses adult-style eye names for the byte-identical young-eye pixels.
        for state in ("Open", "Half", "Closed"):
            assert decode(mm, young + "gEponaEye" + state + "Tex", adult_palette) == \
                decode(oot, adult + "gEponaEye" + state + "Tex", adult_palette)

    out = '''// Generated by scripts/diagnostics/build_epona_masks.py from inspected native OoT/MM materials.
// Immutable UV masks only. Each engine owns its own display-list/texture/cache state.
#ifndef COMBO_EPONA_COSMETIC_MASKS_H
#define COMBO_EPONA_COSMETIC_MASKS_H

#include <array>
#include <cstdint>
#include <string_view>
#include <vector>

namespace EponaMasks {
enum class Part { Coat, WhiteHair, Eyes };

struct Mask {
    uint8_t width;
    uint8_t height;
    std::array<uint32_t, 32> selected;
};

// clang-format off
inline constexpr Mask kMasks[] = {
'''
    for width, height, rows in masks:
        out += f"    {{ {width}, {height}, {{ " + ", ".join(f"0x{row:08X}u" for row in rows) + " } },\n"
    out += '''};

struct Entry {
    std::string_view name;
    std::array<const Mask*, 3> parts;
};

inline constexpr Entry kEntries[] = {
'''
    for name, parts in entries:
        out += '    { "' + name + '", { ' + ", ".join(parts) + " } },\n"
    out += '''};

// clang-format on
inline const Mask* FindMask(std::string_view textureName, Part part) {
    textureName.remove_prefix(textureName.find_last_of('/') == std::string_view::npos
                                  ? 0 : textureName.find_last_of('/') + 1);
    for (const auto& entry : kEntries) {
        if (entry.name == textureName) {
            return entry.parts[static_cast<size_t>(part)];
        }
    }
    return nullptr;
}

// The renderer removes pixels whose mask byte is nonzero. Expand once when a
// display-list copy is cached; rainbow updates only change GPU color commands.
inline std::vector<uint8_t> BuildInverseMask(std::string_view textureName, Part part) {
    const auto* mask = FindMask(textureName, part);
    if (mask == nullptr) {
        return {};
    }
    std::vector<uint8_t> pixels(mask->width * mask->height);
    for (size_t y = 0; y < mask->height; ++y) {
        for (size_t x = 0; x < mask->width; ++x) {
            pixels[y * mask->width + x] = (mask->selected[y] & (uint32_t{1} << x)) == 0;
        }
    }
    return pixels;
}
} // namespace EponaMasks

#endif
'''
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--oot", type=Path, required=True)
    parser.add_argument("--mm", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(build(args.oot, args.mm))


if __name__ == "__main__":
    main()
