"""Derive the GI fit catalog from serialized resources, never held geometry."""
import json
import math
from pathlib import Path
import struct
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ROOT / 'soh/assets/custom/objects/nei_gi_redesign'
OPTIONAL = ROOT / 'tools/nei_gi/OPTIONAL_ASSETS/objects/nei_gi_redesign'
TARGET = ROOT / 'soh/soh/Enhancements/randomizer/NeiGiFrameBounds.inc'

effects = {
    'trident':'Gold', 'roc_boots':'Gold',
    'fire_rod':'Fire', 'ice_rod':'Ice', 'light_rod':'Light', 'deku_leaf':'Leaf',
    'hylia_grace':'Hylia', 'zonai_permafrost':'Zonai', 'demise_destruction':'Demise',
    'elemental_wand':'Light', 'sand_rod':'Sand', 'tornado_rod':'Tornado', 'water_rod':'Water',
    'meteor_rod':'Meteor', 'storm_rod':'Storm', 'shadow_scepter':'Shadow',
    'sheikah_slate':'Slate', 'slate_bomb':'SlateBomb', 'slate_master_cycle':'SlateCycle',
    'slate_stasis':'SlateStasis', 'slate_cryonis':'SlateCryonis', 'slate_sensor':'SlateSensor',
    'phantom_hourglass':'Hourglass', 'shadow_crystal':'DarkCrystal', 'rod_of_seasons':'SeasonCycle',
    'cane_of_somaria':'Somaria', 'cane_of_byrna':'CaneBlue', 'four_sword':'FourSword',
    'kokiri_sword':'KokiriSword', 'mm_kokiri_sword':'MmKokiriSword', 'razor_sword':'RazorSword',
    'gilded_sword':'GildedSword', 'master_sword':'MasterSword', 'true_master_sword':'SwordAura',
    'biggoron_sword':'BiggoronSword', 'great_fairy_sword':'GreatFairySword', 'mario_mask':'MarioMask',
}
preferred = {
    'fire_rod':'kRodShopFit', 'ice_rod':'kRodShopFit', 'light_rod':'kRodShopFit',
    'ball_and_chain':'kBallAndChainShopFit', 'shovel':'kShovelShopFit',
    'hylia_grace':'kSpellShopFit', 'zonai_permafrost':'kSpellShopFit', 'demise_destruction':'kSpellShopFit',
    'time_gate':'kTimeGateShopFit', 'switch_hook':'kSwitchHookShopFit', 'rocs_feather':'kFeatherShopFit',
    'cane_of_somaria':'kSomariaShopFit', 'rocs_cape':'kRocsCapeShopFit',
    'master_sword':'kMasterSwordShopFit', 'true_master_sword':'kMasterSwordShopFit',
    'gilded_sword':'kGildedSwordShopFit', 'biggoron_sword':'kBiggoronSwordShopFit',
    'great_fairy_sword':'kGreatFairySwordShopFit',
}
plain = {'whip','deku_leaf','mogma_mitts','gust_jar','beetle','spinner','minish_cap','lantern','mario_mask','cojiro'}

def number(value):
    return f'{value:.9f}f'

def row(directory):
    slug=directory.name
    points=[tuple(int(v.get(axis)) for axis in ('X','Y','Z'))
            for path in sorted(directory.glob('mesh_*_vtx')) for v in ET.parse(path).getroot()]
    assert points, slug
    words=struct.unpack_from('<16I',(directory/'scale_mtx').read_bytes(),64)
    # Signed integer half and unsigned fractional half of the actual N64 Mtx.
    def element(i):
        half=(words[i//2] >> (16 if i%2==0 else 0)) & 65535
        fraction=(words[8+i//2] >> (16 if i%2==0 else 0)) & 65535
        return (half if half<32768 else half-65536) + fraction/65536
    m=[element(i) for i in range(16)]
    assert all(m[i]==0 for i in (1,2,3,4,6,7,8,9,11,12,13,14)), slug
    assert m[0]==m[5]==m[10] and m[0]>0 and m[15]==1, slug
    scaled=[tuple(v*m[0] for v in p) for p in points]
    low=', '.join(number(min(p[i] for p in scaled)) for i in range(3))
    high=', '.join(number(max(p[i] for p in scaled)) for i in range(3))
    width=number(2*max(math.hypot(p[0],p[2]) for p in scaled))
    fit=preferred.get(slug,'{}' if slug in plain else '{ .85f, 14.f }')
    return f'{{ "{slug}", {{ {low} }}, {{ {high} }}, {width}, Kind::{effects.get(slug,"Neutral")}, {fit} }},'

def generate():
    bundled=sorted(d for d in ASSETS.iterdir() if d.is_dir())
    assert len(bundled)==61
    optional=OPTIONAL/'cojiro'
    rows=[row(d) for d in bundled]
    if optional.exists():
        rows.append(row(optional))
    return '// Generated by tools/nei_gi/generate_frame_bounds.py; serialized OPA + XLU bounds.\n'+'\n'.join(rows)+'\n'

if __name__=='__main__':
    TARGET.write_text(generate())
